
target-version = "py311"
line-length = 100

[lint]

select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "I",  # isort
    "B",  # flake8-bugbear
    "C4", # flake8-comprehensions
    "UP", # pyupgrade
]


ignore = [
    "E501", # line too long, handled by black
    "B008", # do not perform function calls in argument defaults
    "C901", # too complex
    "W191", # indentation contains tabs
    "B904", # ignore error when raise ... from ... is not used
    "E101", # indentation contains tabs
]


[lint.per-file-ignores]
"__init__.py" = ["E401"]

[lint.pydocstyle]
convention = "numpy"
